name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_sonarqube:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Build with Gradle and test SonarQube
        run: ./gradlew build -x test

      - name: Unzip App and Launch SonarQube
        run: |
          cd sonar-application/build/distributions
          unzip *.zip
          cd sonarqube-25.3-SNAPSHOT

          # Set SonarQube to run on port 9000
          echo "sonar.web.port=9000" >> conf/sonar.properties

          ./bin/linux-x86-64/sonar.sh start

      - name: Install JMeter
        run: |
          apt-get update
          apt-get install -y jmeter

      - name: Run Load Test with JMeter
        run: |
          jmeter -n -t tests/sonarqube_load_test.jmx -l test_results.jtl -g test_report

          
      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-report
          path: test_report

