name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_sonarqube:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Install Python and pip
        run: |
          apt-get install -y python3 python3-pip python3-venv

      - name: Set up Virtual Environment
        run: |
          python3 -m venv venv
          . venv/bin/activate

      - name: Install Python Dependencies
        run: |
          . venv/bin/activate
          pip install requests

      - name: Build with Gradle and test SonarQube
        run: ./gradlew build -x test

      - name: Unzip App and Launch SonarQube
        run: |
          cd sonar-application
          cd build
          cd distributions
          unzip *.zip
          cd sonarqube-25.3-SNAPSHOT
          ./bin/linux-x86-64/sonar.sh start
      
      - name: Check SonarQube Port
        run: |
          sleep 10  # Wait for SonarQube to start
          netstat -tulnp | grep java || ss -tulnp | grep java

      - name: Vérifier la disponibilité de SonarQube
        run: |
          . venv/bin/activate
          python test_sonarqube_availability.py
