name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_sonarqube:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Build with Gradle and test SonarQube
        run: ./gradlew build test

      - name: Unzip App and Launch SonarQube
        run: |
          cd sonar-application
          cd build
          cd distributions
          unzip *.zip
          cd sonarqube-25.3-SNAPSHOT
          ./bin/linux-x86-64/sonar.sh start
