name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_sonarqube:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Build with Gradle without test
        run: ./gradlew build -x test

      - name: Run tests for sonar-main
        run: |
          ./gradlew :server:sonar-main:test
      
      - name: Upload Build Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log.gz
          retention-days: 7

      - name: Unzip App and Launch SonarQube
        run: |
          cd sonar-application
          cd build
          cd distributions
          unzip sonar-application-25.2-SNAPSHOT.zip
          cd sonar-application-25.2-SNAPSHOT
          ./bin/linux-x86-64/sonar.sh start
